import Head from 'next/head'
import styles from '../styles/Home.module.css'
import CustomImage from '../components/CustomImage'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Neel Ittyerah Oommen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Work+Sans:wght@800&display=swap" rel="stylesheet"></link>
        <styles>

        </styles>
      </Head>

      <main>
      <div className="bg-black h-full w-full flex flex-col overflow-x-clip snap-y snap-mandatory scrollbar-hide scroll-smooth">
          <div className="relative h-screen flex justify-center items-center snap-center">
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-cyan-400    blur-3xl rounded-full mix-blend-lighten animate-bgAnim"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-yellow-400  blur-3xl rounded-full mix-blend-lighten animate-bgAnim animation-delay-2000"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-purple-400  blur-3xl rounded-full mix-blend-lighten animate-bgAnim animation-delay-4000"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-pink-400    blur-3xl rounded-full mix-blend-lighten animate-bgAnim animation-delay-6000"></div>
              <div className="transform hover:scale-110 hover:text-yellow-200 text-white text-7xl md:text-8xl lg:text-9xl font-workSansFont transition duration-300">Neel<br/>Ittyerah<br/>Oommen</div>
          </div>

          <div className="relative h-screen w-screen flex justify-center items-center px-[2vw] snap-center">
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 md:right-8 bg-cyan-400   blur-2xl mix-blend-lighten animate-squareBgAnim"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 md:right-8 bg-yellow-400 blur-2xl mix-blend-lighten animate-squareBgAnim animation-delay-2000"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 md:right-8 bg-purple-400 blur-2xl mix-blend-lighten animate-squareBgAnim animation-delay-4000"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 md:right-8 bg-pink-400   blur-2xl mix-blend-lighten animate-squareBgAnim animation-delay-6000"></div>   
              <div className="absolute left-0 w-screen">
                <div className="flex flex-col md:flex-row space-y-16 md:space-y-0">
                  <div className="flex flex-col space-y-4 md:space-y-8 md:w-1/2 md:h-screen px-2 md:px-4 justify-center">
                    <div className="transform left-2 md:left-4 text-white text-7xl md:text-8xl lg:text-9xl font-workSansFont font-bold hover:text-cyan-200 transition duration-300">Hey!</div>
                    <div className="transform left-2 md:left-4 text-2xl md:text-3xl lg:text-4xl text-white">My name is <span className="hover:text-yellow-200 transition duration-300">Neel Ittyerah Oommen!</span></div>
                    <div className="text-white text-1xl lg:text-2xl">I am currently a 3rd Year Computer Science Student at <span className="transform hover:text-purple-400 duration-300">VIT Vellore.</span></div>
                    <div className="transform left-2 md:left-4 text-1xl md:text-2xl text-white">I like to code (with experience in
                      <span className="hover:text-purple-400 transform duration-300"> C</span>/
                      <span className="hover:text-cyan-400 transform duration-300">C++</span>/
                      <span className="hover:text-yellow-400 transform duration-300">Python</span>/
                      <span className="hover:text-pink-400 transform duration-300">JavaScript</span>/
                      <span className="hover:text-orange-400 transform duration-300">Java</span>
                      ),<br/> as well as playing and listening to 
                      <span className="hover:text-purple-400 transform duration-300"> music</span>, playing 
                      <span className="hover:text-cyan-400 transform duration-300"> CSGO</span> and watching 
                      <span className="hover:text-yellow-400 transform duration-300"> F1</span>.</div>
                    </div>
                  <div className="flex justify-center items-center md:w-1/2 md:h-screen">
                  <div className='transform w-[300px] md:w-[350px] lg:w-[480px] hover:scale-110  left-4 rounded-xl shadow-2xl duration-300 overflow-hidden'>
                    {/* <CustomImage key={1} imageSrc={'../static/images/profile_image.jpg'}/> */}
                    <img src='../static/images/profile_image.jpg'/>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="relative h-screen w-screen flex justify-center items-center px-[2vw] snap-center">
            <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-cyan-400    blur-3xl rounded-full mix-blend-lighten animate-bgAnim"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-yellow-400  blur-3xl rounded-full mix-blend-lighten animate-bgAnim animation-delay-2000"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-purple-400  blur-3xl rounded-full mix-blend-lighten animate-bgAnim animation-delay-4000"></div>
              <div className="absolute w-72 md:w-80 lg:w-96 h-72 md:h-80 lg:h-96 bg-pink-400    blur-3xl rounded-full mix-blend-lighten animate-bgAnim animation-delay-6000"></div>
            <div className="text-white px-4 font-bold text-3xl md:text-5xl lg:text-7xl transform duration-300">
              More about me coming soon!
            </div>
          </div>
        </div>
        <div className="w-full h-full bg-pink-800">

        </div>
      </main>

    </div>
  )
}
